#!/usr/bin/env node
/**
 * Generate packages/sdk/src/abi.ts from the compiled Foundry artifacts.
 *
 * The SDK must never carry a hand-written ABI: a drifted signature would make
 * the client and the deployed contract disagree about what was enforced.
 * Run after `forge build`; CI re-runs it and fails on a diff.
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const out = (name) =>
  JSON.parse(fs.readFileSync(path.join(root, "contracts/out", `${name}.sol`, `${name}.json`), "utf8"));

const portfolio = out("AirspacePortfolio");
const factory = out("AirspacePortfolioFactory");

const header = `// GENERATED by scripts/sync-abi.mjs from contracts/out — do not edit.
// Regenerate with: pnpm abi:sync   (CI fails if this file is stale.)
`;

const body =
  header +
  `\nexport const airspacePortfolioAbi = ${JSON.stringify(portfolio.abi, null, 2)} as const;\n` +
  `\nexport const airspacePortfolioFactoryAbi = ${JSON.stringify(factory.abi, null, 2)} as const;\n` +
  `\nexport const airspacePortfolioBytecode = ${JSON.stringify(portfolio.bytecode.object)} as const;\n` +
  `\nexport const airspacePortfolioFactoryBytecode = ${JSON.stringify(factory.bytecode.object)} as const;\n`;

const target = path.join(root, "packages/sdk/src/abi.ts");
fs.writeFileSync(target, body);
console.log(`wrote ${path.relative(root, target)} (${portfolio.abi.length} + ${factory.abi.length} entries)`);
